### ISSUE TITLE
sqrt, sqr don't work in some cases

### ISSUE THREAD

**Issue by Noiredd** [ilikeheaps/expr-calc#1]
To reproduce:
compile with `gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4` under Xubuntu 14.04 LTS with `-std=c99`
run, input `sqrt(4)`
desired output: 2, program output: 4
input `1+sqrt(4)`
desired output: 3, program output: 3
input `sqr(10)`
desired output: 100, program output: 10
input `sqr(10)+1`
desired output: 101, program output: 101

**Comment by ilikeheaps** [comment]
It appears that commit [3d6f548ff0ddd8068c62b04fae1281a18e67e88c](https://github.com/ilikeheaps/expr-calc/commit/3d6f548ff0ddd8068c62b04fae1281a18e67e88c) has fixed this bug.
